#!/bin/sh
#
# HTTP Public Key Pinning header pin generator
# by Hanno Böck, https://hboeck.de
# License: CC0 (public domain)
#
# https://tools.ietf.org/html/draft-ietf-websec-key-pinning-20

if [ -z "$1" ]; then
	echo "HKP header generator according to"
	echo "http://tools.ietf.org/html/draft-ietf-websec-key-pinning-20"
	echo ""
	echo "Usage: $0 [files]"
	echo ""
	echo "[files] should contain at least 2 files and can be of type"
	echo ".crt or .pem (certificate), .csr (certificate request) or"
	echo ".key (private key)"
	exit 1
fi

head="Public-Key-Pins: max-age=5184000; "

c=0
for f in "$@"; do
	e=`printf %s "$f"|tail -c 4`
	echo $e
	if [ "$e" = ".crt" -o "$e" = ".pem" ]; then
		pkey=`openssl x509 -pubkey -noout -in $f`
	elif [ "$e" = ".csr" ]; then
		pkey=`openssl req -pubkey -noout -in $f`
	elif [ "$e" = ".key" ]; then
		pkey=`openssl pkey -in $f -pubout`
	else
		echo "$f is not a valid file format"
		exit 255
	fi
	c=$(($c + 1))
	phash=`echo "$pkey"|grep -vF PUBLIC|openssl enc -base64 -d|openssl dgst -binary -sha256|openssl enc -base64`
	head="${head}pin-sha256=\"$phash\";"
done

[ $c -eq 1 ] && echo "Warning: HKP requires at least 2 keys" >&2
echo $head

